FROM node:8.1.2

MAINTAINER kcod <ganadara135@gmail.com>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY package.json /usr/src/app/
RUN npm install && npm cache clean --force
COPY . /usr/src/app

EXPOSE  3000 1999 80

CMD [ "npm", "start" ]

#컨테이너  생성 명령어
#docker run --name myappc -p 3000:3000 -v d:\\mychain:/usr/src/app myapp node server.js
